#ifndef INTERCOM_H
#define INTERCOM_H

#include "core.h"

///////////////////////////////////////////////////////////////
// Public Types
///////////////////////////////////////////////////////////////

typedef enum _REQUEST_TYPE
{
  REQUEST_TYPE_NONE,
  REQUEST_TYPE_INFO,
  REQUEST_TYPE_SHUTDOWN,
  REQUEST_TYPE_SCAN,
  REQUEST_TYPE_BREAK,
  REQUEST_TYPE_MEMORY,
} REQUEST_TYPE, * PREQUEST_TYPE;

typedef enum _INFO_TYPE
{
  INFO_TYPE_NONE,
  INFO_TYPE_PROCESS,
} INFO_TYPE, * PINFO_TYPE;

typedef enum _SCAN_TYPE
{
  SCAN_TYPE_NONE,
  SCAN_TYPE_RESET,
  SCAN_TYPE_FIRST_ARRAY_OF_BYTES,
  SCAN_TYPE_NEXT_CHANGED,
  SCAN_TYPE_NEXT_UNCHANGED,
  SCAN_TYPE_UNDO,
} SCAN_TYPE, * PSCAN_TYPE;

typedef enum _BREAK_TYPE
{
  BREAK_TYPE_NONE,
  BREAK_TYPE_SET,
  BREAK_TYPE_CLEAR,
} BREAK_TYPE, * PBREAK_TYPE;

typedef enum _MEMORY_TYPE
{
  MEMORY_TYPE_NONE,
  MEMORY_TYPE_KERNEL,
  MEMORY_TYPE_PROCESS,
} MEMORY_TYPE, * PMEMORY_TYPE;

typedef enum _MEMORY_OPERATION_TYPE
{
  MEMORY_OPERATION_TYPE_NONE,
  MEMORY_OPERATION_TYPE_READ,
  MEMORY_OPERATION_TYPE_WRITE,
} MEMORY_OPERATION_TYPE, * PMEMORY_OPERATION_TYPE;

#endif